<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>genderFemale</name>
   <tag></tag>
   <elementGuidId>5bbbad23-8fde-46ac-955c-29240b4f3fc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div/div[2]/div[2]/div[2]/form/div[3]/div[2]/div[2][count(. | //input[@id = 'gender-radio-2' and @type = 'radio']) = count(//input[@id = 'gender-radio-2' and @type = 'radio'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gender-radio-2</value>
      <webElementGuid>044b97d3-fadf-4393-8fdf-e580985b62c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ac86fa25-cde5-4a56-ad80-a8b868e54a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div/div[2]/div[2]/div[2]/form/div[3]/div[2]/div[2]</value>
      <webElementGuid>9597cb35-52c8-4671-a7fd-a6f35f855d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae49cf5d-10d7-4b7c-927f-9a1d8b10b3fc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
